### ISSUE TITLE
拡張機能のAPIリファレンスでマクロエラーが出る

### ISSUE THREAD

**Issue by Uemmra3** [mozilla-japan/translation#261]
+ エラー対象マクロ
{{WebExtExamples}}
{{WebExtBrowserCompat}}

+ 確認対象ページ
developer.mozilla.org/en-US/Add-ons/WebExtensions/API/bookmarks/BookmarkTreeNodeType
developer.mozilla.org/ja/Add-ons/WebExtensions/API/bookmarks/BookmarkTreeNodeUnmodifiable

**Comment by Uemmra3** [comment]
試しにマクロを入れてみたけど、マクロエラー再現せず。。

**Comment by momdo** [comment]
https://developer.mozilla.org/ja/Add-ons/WebExtensions/API/bookmarks/BookmarkTreeNodeType を編集してプレビューしたらこんな感じで怒られました。
```
このページにスクリプトエラーがあります。サイト編集者によって解決されるまでの間は、以下の部分的な内容のみが表示可能です。

エラー情報を隠す
MDN プロファイルを持っている人なら誰でもドキュメントを編集して問題点を修正できます。まずは KumaScript トラブルシューティングガイド を見てみてください。

エラーの種類: TemplateExecutionError マクロのコード: WebExtExamples (マクロを表示) マクロの解析: WebExtExamples ([]) エラーテキスト詳細: 
Problem executing template WebExtExamples:
   24 | 
   25 | <p>{{WebExtExamples}}</p>
   26 | null
--------^

TypeError: ejs:1
 >> 1| <%
    2| 
    3| /*
    4| The "examples.json" file from the https://github.com/mdn/webextensions-examples

Cannot read property 'split' of undefined
    at eval (eval at compile (/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:105:22)
    at returnedFn (/node_modules/ejs/lib/ejs.js:580:17)
    at /app/lib/kumascript/templates.js:71:26
```

**Comment by Uemmra3** [comment]
あ、プレビューの時だけエラーになるのですね(こちらでも再現)。
根拠はなくてアレなのですが、保存したら出ないエラーな気もします。

バグっぽいので登録してみました。
https://bugzilla.mozilla.org/show_bug.cgi?id=1439961

**Comment by Uemmra3** [comment]
プレビューモードでマクロが動かないのは不便なので、スタッフの間では使わない(バグを直すかプレビュー機能をなくしてしまうか)ことになっているようです。
https://bugzilla.mozilla.org/show_bug.cgi?id=1363908
